apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    apps: nginx
    tier: backend
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - production
      containers:
        - name: nginx-container
          image: nginx:1.25
          resources:
            requests:
              cpu : "500m"
              memory: "1Gi"
            limits: 
              cpu : "1000m"
              memory: "2Gi"