apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-service
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd-container
          image: fluent/fluentd:v1.17.1-1.0